version: '3.8'

services:
  db-canchas:
    image: postgres:15
    container_name: postgres-canchas-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: reservascanchas
    ports:
      - "5432:5432"
    restart: always